attributes:
  metadata:
    label: "Detach Keystone Plugin"
    weight: 90
  yaml_additional_config:
    description: |
      This field contains free form YAML to provide extra parameters.
    type: "textarea"
    weight: 52
    value: |
      #Uncomment and adjust to enable remote keystone
      #remote_keystone: 10.20.5.22
      #keystone:
      #  admin_token: REMOTE_KEYSTONE_TOKEN
    label: "Additional config"
    regex:
      source: '.+'
      error: "This field should not be empty"

